DROP DATABASE IF EXISTS `books`;
CREATE DATABASE IF NOT EXISTS `books`;
USE `books`;

CREATE TABLE IF NOT EXISTS `Authors` (
AuthorID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`AuthorID`),
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL,
Phone VARCHAR(50),
Email VARCHAR(50),
Address VARCHAR(200),
City VARCHAR(50),
State VARCHAR(50),
INDEX `AuthorID` (`AuthorID` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `Publishers` (
PublisherID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`PublisherID`),
PublisherName VARCHAR(100) NOT NULL,
Address VARCHAR(200),
City VARCHAR(50),
State VARCHAR(50),
INDEX `PublisherID` (`PublisherID` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE IF NOT EXISTS `Genres` (
GenreID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`GenreID`),
GenreName VARCHAR(100) NOT NULL,
GenreDescription VARCHAR(200),
Fiction BOOLEAN,
INDEX `GenreID` (`GenreID` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `Books` (
BookID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(`BookID`),
PublisherID INT,
FOREIGN KEY (`PublisherID`) REFERENCES `Publishers` (`PublisherID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
GenreID INT,
FOREIGN KEY (`GenreID`) REFERENCES `Genres` (`GenreID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
Title VARCHAR(100) NOT NULL,
UnitPrice DECIMAL(5, 2),
Contract VARCHAR(100),
Comments VARCHAR(500),
PublicationDate DATE,
INDEX `BookID` (`BookID` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `BookAuthors` (
AuthorID INT NOT NULL AUTO_INCREMENT,
FOREIGN KEY (`AuthorID`) REFERENCES `Authors` (`AuthorID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
BookID INT NOT NULL,
FOREIGN KEY (`BookID`) REFERENCES `Books` (`BookID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
PRIMARY KEY(`BookID`),
Royalty DECIMAL(5, 2),
INDEX `AuthorID` (`AuthorID` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;